name: xgboost
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.6
  - dask==2021.11.1
  - distributed==2021.11.1
  - cloudpickle==2.0.0
  - scipy
  - scikit-learn
  - pyarrow
  - fastparquet
  - jupyterlab
  - dask-labextension
  - ipykernel
  - s3fs
  - coiled
  - numpy
  - pandas
  - dask-ml
  - ipython
  - ipywidgets
  - lz4==3.1.3
  - xgboost>=1.5
