name: energy-landscape
channels:
  - conda-forge
dependencies:
  - coiled
  - dask-ml
  - dask>=2.23.0
  - dask-labextension
  - distributed>=2.23.0
  - fastparquet
  - ipywidgets
  - jupyterlab
  - matplotlib
  - pandas>=1.1.0
  - pip
  - pip:
    - fastdtw
  - seaborn
  - s3fs
  - scikit-learn
